import Head from 'next/head';
import React from 'react';
import { useForm } from "react-hook-form";
import { toast } from 'react-toastify';

const Login = () => {
    const { register, handleSubmit, reset } = useForm();
    const onSubmit = data => {
        if (data.password !== data.rePassword) {
            return toast.error("Password didn't match!");

        } else {
            console.log(data);
        }
    };

    const handleGoogleSignIn = () => { }
    const handleFacaebookSignIn = () => { }

    return (
        <div>
            <Head>
                <title>ezymart | login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='position-absolute top-50 start-50 translate-middle'>
                <form
                    onSubmit={handleSubmit(onSubmit)}
                    className="d-flex flex-column gap-2"
                >
                    <input
                        type="text"
                        {...register("firstName", { required: true, maxLength: 20 })}
                    />
                    <input
                        type="text"
                        {...register("lastName", { required: true, maxLength: 20 })}
                    />
                    <input
                        type="email"
                        {...register("email", { required: true })}
                    />
                    <input
                        type="password"
                        {...register("password", { required: true })}
                    />
                    <input
                        type="password"
                        {...register("rePassword", { required: true })}
                    />
                    <input type="submit" />
                </form>
            </div>
        </div>
    );
};

export default Login;